!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 128
  - - cg_max_steps
    - 30
  - - gae_lambda
    - 0.95
  - - gamma
    - 0.99
  - - learning_rate
    - 1.9904955094948545e-05
  - - n_critic_updates
    - 25
  - - n_envs
    - 1
  - - n_steps
    - 2048
  - - n_timesteps
    - 5000000.0
  - - normalize
    - true
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict( activation_fn=torch.nn.ReLU, net_arch=[dict(pi=[64, 64], vf=[64, 64])]
      )
  - - target_kl
    - 0.01
